### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by OwenRay** [lalbert/magento2-fr_fr#109]
Small problem with the installation:

in some shells the following command:
`composer require lalbert/magento2-fr_fr:*`
leads to something like: `zsh: no matches found: lalbert/magento2-fr_fr:*`

I suggest changing this to:
`composer require "lalbert/magento2-fr_fr:*"`

**Comment by lucalbert** [comment]
Hi @OwenRay,

Thanks for your feedback.
Sorry for my late reply.

I totally understand the problem. 
This is caused by the globbing feature of zsh. It is not specific to composer.

The [official documentation of composer](https://getcomposer.org/doc/03-cli.md#require) does not specify the quotes, and mostly (if not all the time) the quotation marks are not specified in the installation documentation for other packages.

Also, to stay as simple as possible and consistent with the community, I do not think it appropriate to add the quotes.

Thanks again.
